use_frameworks!

platform :ios, '11.0'

target 'BSGUtilities' do
  pod "BSGUtilities", :path => "../"
  pod "Reachability"

  target 'Tests' do
    inherit! :search_paths
  end
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end