source 'https://github.com/CocoaPods/Specs.git'

target 'BSGUtilities', :exclusive => true do
  pod "BSGUtilities", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BSGUtilities", :path => "../"

  #pod 'Specta', '~> 1.0.0'
  #pod 'Expecta'
  #pod 'FBSnapshotTestCase'
  #pod 'Expecta+Snapshots'
end
